/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.LinguaLens;
//import javax.swing.ImageIcon;
import java.awt.*;



public class NewUIBelle extends javax.swing.JFrame {

    //ImageIcon imageToTranslate = new ImageIcon("userfile from file chooser");
    
    /**
     * Creates new form NewUIBelle
     */
    public NewUIBelle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        translationInternalFrame = new javax.swing.JInternalFrame();
        translationScrollPane = new javax.swing.JScrollPane();
        translationTextArea = new javax.swing.JTextArea();
        translationLabel = new javax.swing.JLabel();
        ogtextInternalFrame = new javax.swing.JInternalFrame();
        ogtextScrollPane = new javax.swing.JScrollPane();
        ogtextTextArea = new javax.swing.JTextArea();
        ogtextLabel = new javax.swing.JLabel();
        historyInternalFrame = new javax.swing.JInternalFrame();
        historyButton2 = new javax.swing.JButton();
        historyButton1 = new javax.swing.JButton();
        historyButton3 = new javax.swing.JButton();
        historyButton4 = new javax.swing.JButton();
        historyButton5 = new javax.swing.JButton();
        historyButton6 = new javax.swing.JButton();
        historyButton7 = new javax.swing.JButton();
        historyButton8 = new javax.swing.JButton();
        historyButton9 = new javax.swing.JButton();
        historyButton10 = new javax.swing.JButton();
        imageInternalFrame = new javax.swing.JInternalFrame();
        translateButton = new javax.swing.JButton();
        openfileButton = new javax.swing.JButton();
        snipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LinguaLens");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1200, 675));
        setMinimumSize(new java.awt.Dimension(1200, 675));
        setPreferredSize(new java.awt.Dimension(1200, 675));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));

        translationInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        translationInternalFrame.setIconifiable(true);
        translationInternalFrame.setResizable(true);
        translationInternalFrame.setTitle("Translated Text");
        translationInternalFrame.setFocusable(false);
        translationInternalFrame.setMaximumSize(new java.awt.Dimension(450, 337));
        translationInternalFrame.setPreferredSize(new java.awt.Dimension(450, 337));
        translationInternalFrame.setRequestFocusEnabled(false);
        translationInternalFrame.setVerifyInputWhenFocusTarget(false);
        translationInternalFrame.setVisible(true);

        translationTextArea.setEditable(false);
        translationTextArea.setColumns(20);
        translationTextArea.setLineWrap(true);
        translationTextArea.setRows(5);
        translationTextArea.setWrapStyleWord(true);
        translationTextArea.setFocusable(false);
        translationTextArea.setPreferredSize(new java.awt.Dimension(100, 100));
        translationScrollPane.setViewportView(translationTextArea);

        translationLabel.setText("Translated to: ");

        javax.swing.GroupLayout translationInternalFrameLayout = new javax.swing.GroupLayout(translationInternalFrame.getContentPane());
        translationInternalFrame.getContentPane().setLayout(translationInternalFrameLayout);
        translationInternalFrameLayout.setHorizontalGroup(
            translationInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(translationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addComponent(translationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        translationInternalFrameLayout.setVerticalGroup(
            translationInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, translationInternalFrameLayout.createSequentialGroup()
                .addComponent(translationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(translationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ogtextInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ogtextInternalFrame.setIconifiable(true);
        ogtextInternalFrame.setTitle("Original Text");
        ogtextInternalFrame.setFocusable(false);
        ogtextInternalFrame.setMaximumSize(new java.awt.Dimension(450, 337));
        ogtextInternalFrame.setPreferredSize(new java.awt.Dimension(450, 337));
        ogtextInternalFrame.setRequestFocusEnabled(false);
        ogtextInternalFrame.setVerifyInputWhenFocusTarget(false);
        ogtextInternalFrame.setVisible(true);

        ogtextScrollPane.setPreferredSize(new java.awt.Dimension(224, 86));

        ogtextTextArea.setEditable(false);
        ogtextTextArea.setColumns(20);
        ogtextTextArea.setLineWrap(true);
        ogtextTextArea.setRows(5);
        ogtextTextArea.setWrapStyleWord(true);
        ogtextTextArea.setFocusable(false);
        ogtextScrollPane.setViewportView(ogtextTextArea);

        ogtextLabel.setText("Detected Language: ");

        javax.swing.GroupLayout ogtextInternalFrameLayout = new javax.swing.GroupLayout(ogtextInternalFrame.getContentPane());
        ogtextInternalFrame.getContentPane().setLayout(ogtextInternalFrameLayout);
        ogtextInternalFrameLayout.setHorizontalGroup(
            ogtextInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ogtextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
            .addComponent(ogtextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ogtextInternalFrameLayout.setVerticalGroup(
            ogtextInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ogtextInternalFrameLayout.createSequentialGroup()
                .addComponent(ogtextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ogtextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        historyInternalFrame.setTitle("History");
        historyInternalFrame.setToolTipText("");
        historyInternalFrame.setFocusable(false);
        historyInternalFrame.setMaximumSize(new java.awt.Dimension(285, 637));
        historyInternalFrame.setMinimumSize(new java.awt.Dimension(285, 637));
        historyInternalFrame.setPreferredSize(new java.awt.Dimension(285, 637));
        historyInternalFrame.setVisible(true);

        historyButton2.setEnabled(false);
        historyButton2.setFocusable(false);
        historyButton2.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton2.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton2.setPreferredSize(new java.awt.Dimension(273, 60));
        historyButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButton2ActionPerformed(evt);
            }
        });

        historyButton1.setText("This is translated text blah blah blah blah blah blah. Ajsflas to English 11/05/2023");
        historyButton1.setToolTipText("default...");
        historyButton1.setFocusable(false);
        historyButton1.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton1.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton1.setPreferredSize(new java.awt.Dimension(273, 60));
        historyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButton1ActionPerformed(evt);
            }
        });

        historyButton3.setEnabled(false);
        historyButton3.setFocusable(false);
        historyButton3.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton3.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton3.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton4.setEnabled(false);
        historyButton4.setFocusable(false);
        historyButton4.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton4.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton4.setPreferredSize(new java.awt.Dimension(273, 60));
        historyButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButton4ActionPerformed(evt);
            }
        });

        historyButton5.setEnabled(false);
        historyButton5.setFocusable(false);
        historyButton5.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton5.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton5.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton6.setEnabled(false);
        historyButton6.setFocusable(false);
        historyButton6.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton6.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton6.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton7.setEnabled(false);
        historyButton7.setFocusable(false);
        historyButton7.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton7.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton7.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton8.setEnabled(false);
        historyButton8.setFocusable(false);
        historyButton8.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton8.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton8.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton9.setEnabled(false);
        historyButton9.setFocusable(false);
        historyButton9.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton9.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton9.setPreferredSize(new java.awt.Dimension(273, 60));

        historyButton10.setEnabled(false);
        historyButton10.setFocusable(false);
        historyButton10.setMaximumSize(new java.awt.Dimension(273, 60));
        historyButton10.setMinimumSize(new java.awt.Dimension(273, 60));
        historyButton10.setPreferredSize(new java.awt.Dimension(273, 60));

        javax.swing.GroupLayout historyInternalFrameLayout = new javax.swing.GroupLayout(historyInternalFrame.getContentPane());
        historyInternalFrame.getContentPane().setLayout(historyInternalFrameLayout);
        historyInternalFrameLayout.setHorizontalGroup(
            historyInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyInternalFrameLayout.createSequentialGroup()
                .addGroup(historyInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historyButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        historyInternalFrameLayout.setVerticalGroup(
            historyInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyInternalFrameLayout.createSequentialGroup()
                .addComponent(historyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historyButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageInternalFrame.setTitle("Image");
        imageInternalFrame.setFocusable(false);
        imageInternalFrame.setMaximumSize(new java.awt.Dimension(900, 300));
        imageInternalFrame.setMinimumSize(new java.awt.Dimension(900, 300));
        imageInternalFrame.setPreferredSize(new java.awt.Dimension(900, 300));
        imageInternalFrame.setVisible(true);

        translateButton.setText("Translate");
        translateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateButtonActionPerformed(evt);
            }
        });

        openfileButton.setText("Open File");
        openfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openfileButtonActionPerformed(evt);
            }
        });

        snipButton.setText("Use Snipping Tool");

        javax.swing.GroupLayout imageInternalFrameLayout = new javax.swing.GroupLayout(imageInternalFrame.getContentPane());
        imageInternalFrame.getContentPane().setLayout(imageInternalFrameLayout);
        imageInternalFrameLayout.setHorizontalGroup(
            imageInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imageInternalFrameLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(openfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(translateButton)
                .addGap(190, 190, 190))
            .addGroup(imageInternalFrameLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(snipButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imageInternalFrameLayout.setVerticalGroup(
            imageInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imageInternalFrameLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(snipButton)
                .addGap(18, 18, 18)
                .addGroup(imageInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(translateButton)
                    .addComponent(openfileButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(historyInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ogtextInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(translationInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(984, 984, 984))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(historyInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ogtextInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(translationInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(imageInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        try {
            translationInternalFrame.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        try {
            ogtextInternalFrame.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>                        

    private void translateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        translationTextArea.setText("Translated text goes here wooo yay.");
        ogtextTextArea.setText("ADJhjkskjas hdawh FHOIAJfoisaj foidsfj oiHAIOFh oifh OIAHF fiasoifh asoifh oiN OIasfo ofie OIHf oiSA");
        
        translationLabel.setText("Translated To: English");
        ogtextLabel.setText("Detected Language: Aasfg");
    }                                               

    private void historyButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void historyButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void historyButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    
    private void openfileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        chooseImage();
    }                                              

    
    public static String chooseImage() {
        FileDialog fileDialog = new FileDialog((Frame) null, "Select an Image", FileDialog.LOAD);
        fileDialog.setFile("*.jpg;*.jpeg;*.png;*.gif;*.bmp"); // Filter for image files
        fileDialog.setVisible(true);

        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();

        if (directory != null && filename != null) {
            return directory + filename;
        }
        return null;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUIBelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUIBelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUIBelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUIBelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUIBelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton historyButton1;
    private javax.swing.JButton historyButton10;
    private javax.swing.JButton historyButton2;
    private javax.swing.JButton historyButton3;
    private javax.swing.JButton historyButton4;
    private javax.swing.JButton historyButton5;
    private javax.swing.JButton historyButton6;
    private javax.swing.JButton historyButton7;
    private javax.swing.JButton historyButton8;
    private javax.swing.JButton historyButton9;
    private javax.swing.JInternalFrame historyInternalFrame;
    private javax.swing.JInternalFrame imageInternalFrame;
    private javax.swing.JInternalFrame ogtextInternalFrame;
    private javax.swing.JLabel ogtextLabel;
    private javax.swing.JScrollPane ogtextScrollPane;
    private javax.swing.JTextArea ogtextTextArea;
    private javax.swing.JButton openfileButton;
    private javax.swing.JButton snipButton;
    private javax.swing.JButton translateButton;
    private javax.swing.JInternalFrame translationInternalFrame;
    private javax.swing.JLabel translationLabel;
    private javax.swing.JScrollPane translationScrollPane;
    private javax.swing.JTextArea translationTextArea;
    // End of variables declaration                   
}
